config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#index'

  resources :users
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  get '/cities/most', to: 'cities#most'
  get '/restaurants/most-reviewed', to: 'restaurants#most'

  resources :restaurants do
    resources :reviews, only: [:new, :index, :create]
  end
  resources :cities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :restaurants
    has_many :wishlists

    validates :name, presence: true, uniqueness: { case_sensitive: false }

    scope :most_restaurants, -> { City.left_joins(:restaurants).group(:city_id).order('COUNT(restaurants.id) DESC').limit(1) }

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :reviews
    has_many :users, through: :reviews
    belongs_to :city
    has_many :wishlists

    validates :name, presence: true
    validate :not_the_same

    scope :most_reviewed, -> { Restaurant.left_joins(:reviews).group(:restaurant_id).order('COUNT(restaurants.id) DESC').limit(1) }
    scope :high_to_low_rating, -> { Restaurant.left_joins(:reviews).group(:id).order('AVG(star_rating) DESC') }

    def not_the_same
        if Restaurant.find_by(name: name, street_address: street_address)
            errors.add(:street_address, "has already been added for this restaurant.")
        end
    end

    def self.search(search)
        if search
            city = City.find_by(name: search)
            if city
                self.where(city_id: city)
            else
                Restaurant.all
            end
        else
            Restaurant.all
        end
    end

    def city_attributes=(city)
        self.city = City.find_or_create_by(id: city_id)
        self.city.update(city)
    end

end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :restaurant

    validates :content, presence: true, length: { maximum: 500 }
    validates_numericality_of :star_rating, :greater_than_or_equal_to => 0, :less_than_or_equal_to => 5 

    scope :high_to_low, -> { order(star_rating: :desc) }
    scope :low_to_high, -> { order(star_rating: :asc) }

end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews
    has_many :restaurants, through: :reviews
    has_many :wishlists
    has_many :cities, through: :wishlists

    has_secure_password

    validates :password, length: { minimum: 8 }
    validates :username, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }

    VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL }, uniqueness: { case_sensitive: false }



    def self.create_user_from_google(auth)
        self.find_or_create_by(email: auth[:info][:email]) do |u|
            u.password = SecureRandom.hex
            u.username = auth[:info][:name]
        end

    end
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
    belongs_to :city
    belongs_to :user
    belongs_to :restaurant

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :require_login

    private
        def current_user
            @current_user ||= User.find_by_id(session[:user_id])
            #or/equals will only call DB once if using it 1+ times in a method
        end

        def require_login
            if !session.include? :user_id
                redirect_to '/users/new'
            end
        end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
   
    def most
        @city = City.most_restaurants[0]
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    
    def index
        @user = current_user
        @restaurants = Restaurant.search(params[:search]).high_to_low_rating
    end

    def new
        @restaurant = Restaurant.new
        #byebug
        @restaurant.build_city
    end

    def create
        @restaurant = Restaurant.new(restaurant_params)
        
        if @restaurant.save
            redirect_to restaurant_path(@restaurant)
        else
            @restaurant.build_city
            render :new
        end
    end

    def show
        @restaurant = Restaurant.find_by(id: params[:id])
    end

    def most
        @restaurant = Restaurant.most_reviewed[0]
    end

    private

        def restaurant_params
            params.require(:restaurant).permit(:name, :street_address, :genre, :city_id, :search, city_attributes: [:name])
        end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def index
        #byebug
        @restaurant = Restaurant.find_by(id: params[:restaurant_id])
        if params[:review] == 'High to Low'
            @reviews = Review.high_to_low
        elsif params[:review] == 'Low to High'
            @reviews = Review.low_to_high
        else
            @reviews = @restaurant.reviews
        end
    end

    def new
        @restaurant = Restaurant.find_by(id: params[:restaurant_id])
        @review = @restaurant.reviews.build
    end

    def create
        #byebug
        @restaurant = Restaurant.find_by(id: review_params[:restaurant_id])
        @review = current_user.reviews.build(review_params)
        if @review.save
            #byebug
            redirect_to restaurant_reviews_path(@restaurant)
        else
            render :new
        end
    end

    private

    def review_params
        params.require(:review).permit(:title, :content, :star_rating, :restaurant_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :require_login

    def index

    end

    def new

    end

    def create
        @user = User.find_by(email: params[:user][:email])
        if @user && @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id
            redirect_to restaurants_path
        else
            flash[:error] = "Sorry, we were unable to log you in"
            redirect_to login_path
        end
    end

    def destroy
        session.delete(:user_id)
        redirect_to root_path
    end

    def omniauth
        @user = User.create_user_from_google(auth)

        @user.username = ("#{@user.username}" + "#{@user.id}").gsub(/\s+/, "")
        @user.save

        session[:user_id] = @user.id
        redirect_to restaurants_path
    end

    private

    def auth
        request.env['omniauth.auth']
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :require_login, only: [:new, :create]


    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to restaurants_path
        else
            render :new
        end

    end

    def show
        #byebug
        @user = current_user
        if !@user
            redirect_to root_path
        end
    end

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper

    def logged_in?
        !!session[:user_id]
      end
end

app/helpers/cities_helper.rb
module CitiesHelper
    
end

app/helpers/reivews_helper.rb
module ReviewsHelper
    
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
    
end

app/helpers/reviews_helper.rb
module ReviewsHelper

    def show_reviews(reviews, restaurant)
        if @reviews == []
            render partial: "empty", locals: { restaurant: @restaurant }
        else
            render partial: "reviews", locals: { reviews: @reviews }
        end
    end

end

app/helpers/users_helper.rb
module UsersHelper
    
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
    
end

app/views/cities/most.html.erb
<h1>The City With The Most Restaurants:</h1> <h2><%= @city.name %></h2>

app/views/layouts/_errors.html.erb
<div class="fields_with_errors">
  <% if object.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>
  
      <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantsOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <% if logged_in? %>
        <nav class="navbar navbar-light bg-light">
          <a class="navbar-brand" href="/">RoR</a>
          <form class="form-inline">
            <%= link_to "Log Out", logout_path, method: :delete, :class =>"btn btn-outline-primary" %>
            <div style="padding-left: 10px;">
              <a class="btn btn-outline-primary" href="/restaurants" role="button">Home</a>
            </div>
            <div style="padding-left: 10px;">
              <a class="btn btn-outline-primary" href="/restaurants/new" role="button">Add New Restaurant</a>
            </div>
          </form>
        </nav>
      <% else %>
        <nav class="navbar navbar-light bg-light">
          <a class="navbar-brand" href="/">RoR</a>
          <form class="form-inline">
            <a class="btn btn-outline-primary" href="/login" role="button">Login</a>
            <div style="padding-left: 10px;">
                <a class="btn btn-outline-primary" href="/auth/google_oauth2" role="button">Login with Google</a>
            </div>
            <div style="padding-left: 10px;">
              <a class="btn btn-outline-success" href="/signup" role="button">Sign Up</a>
            </div>
          </form>
        </nav>
      <% end %>
    </div>
    <div class="card">
      <div class="card-body">
    
        <%= yield %>
    
      </div>
    </div>
    <div class="footer-margin">
      <footer class="card-footer bg-light footer-font-style text-muted footer-position">
        <a href="https://github.com/heathermiller114/restaurants_on_rails">Github</a>
      </footer>
    </div>

  </body>
</html>

app/views/restaurants/index.html.erb
<div class="title">
    <h1>Hello, <%= @user.username %>. Where do you want to go?</h1>
</div>
<br><br>
<div class="search">
    <h2>Search by City:</h2>
        <%= form_tag(restaurants_path, method: :get) do %>
            <%= text_field_tag(:search, params[:search]) %>
            <%= submit_tag ("Search"), :class =>"btn btn-outline-dark" %>
        <% end %>
</div>
<br><br>
<div class="suggestions">
    <h4>Top Suggestions by Highest Rated:</h4>
        <br>
        <% @restaurants.each do |restaurant| %>
            <ul>
                <li><%= link_to restaurant.name, restaurant_path(restaurant) %> - <%= restaurant.city.name %></li><br>
            </ul>
        <% end %>
</div>

app/views/restaurants/most.html.erb
<h1>The Most Reviewed Restaurant Is:</h1> <h2><%= @restaurant.name %></h2>

app/views/restaurants/new.html.erb
<h1>Make a New Restaurant</h1>

<%= render partial: "layouts/errors", locals: {object: @restaurant} %>

<%= form_for @restaurant do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br><br>
    <%= f.label :street_address %>
    <%= f.text_field :street_address %><br><br>
    <%= f.label :genre %>
    <%= f.text_field :genre %><br><br>

    <p>Select a city:</p>
    <%= f.collection_select :city_id, City.all, :id, :name, include_blank: 'Select One' %>

    <p>Or add a new one:</p>
    <%= f.fields_for :city, @restaurant.build_city do |city_fields| %>
        <%= city_fields.label :name %>
        <%= city_fields.text_field :name %>
    <% end %><br><br>

    <%= f.submit "Create Restaurant" %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h3><%= @restaurant.street_address %></h3>
<h3><%= @restaurant.city.name %></h3>
<h4><%= @restaurant.genre %> </h4>

<%= link_to "Write a Review", new_restaurant_review_path(@restaurant) %>
<%= link_to "Read Reviews", restaurant_reviews_path(@restaurant)%>

app/views/reviews/_empty.html.erb
<h3>Looks like there aren't any reviews yet! Been here before? Write one <%= link_to "here!", new_restaurant_review_path(@restaurant) %></h3>

app/views/reviews/_reviews.html.erb
<% @reviews.each do |review| %>
    <h3>Written by <%= review.user.username %> on <%= review.created_at.strftime("%b %d, %Y") %></h3>
        <%= review.title %><br><br>
        <%= review.content %>
        <h4>Star rating: <%= review.star_rating %></h4>
    <br><br>
<% end %>

app/views/reviews/index.html.erb
<h1>Reviews for <%= link_to @restaurant.name, restaurant_path(@restaurant) %></h1>

<div>
  <h5>Filter Reviews:</h5>
  <%= form_tag("/restaurants/#{@restaurant.id}/reviews", method: 'get') do %>
    <%= select_tag 'review', options_for_select(['High to Low', 'Low to High']), include_blank: "Sort Reviews" %>
    <%= submit_tag "Filter" %>
  <% end %>
</div>

<div>
  <%= show_reviews(@reviews, @restaurant) %>
</div>

app/views/reviews/new.html.erb
<h1>Add a Review for <%= @restaurant.name %> in <%= @restaurant.city.name %></h1><br>

<%= render partial: "layouts/errors", locals: {object: @review} %>

<%= form_for [@restaurant, @review] do |f| %>

    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <br>
    <div>
        <%= f.label :content %>
        <%= f.text_area :content %>
    </div>
    <br>
    <div>
        <%= f.label :star_rating %>
        <%= f.number_field :star_rating, min:0, max:5 %>
    </div>
    <br>
    <%= f.hidden_field :restaurant_id%>

    <%= f.submit %>


<% end %>

app/views/user/new.html.erb
<%= form_for @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.submit "Create User" %>
<%= end %>

app/views/users/new.html.erb
<div class="title">
    <h1>Signup:</h1>
</div>
<br><br>
<div class="fields_with_errors">
    <%= render partial: "layouts/errors", locals: {object: @user} %>
</div>

<div class="title">
    <%= form_for @user do |f| %>
        <%= f.label :username %>
        <%= f.text_field :username %><br><br>

        <%= f.label :email %>
        <%= f.email_field :email %><br><br>
        
        <%= f.label :password %>
        <%= f.password_field :password %><br><br>
        <%= f.submit "Create User", :class =>"btn btn-outline-dark" %>
    <% end %>
</div>

app/views/users/show.html.erb
<h1> Welcome, <%= @user.username %></h1>